#!/usr/bin/env python3
"""Regenerates server/src/search-unicode-tables.json from the bundled SQLCipher tokenizer.

The same probe, the same three arrays, as SearchUnicodeTables.swift, in a form Bun can import
without parsing Swift. `server/src/search.test.ts` recomputes the manifest's `tables` digest from
this file, so the two copies cannot drift apart without a test failing on Linux CI, and
`verify-search-tables.sh` diffs this file against a fresh probe on macOS, so neither can drift
from the engine.

    python3 scripts/generate-search-unicode-tables-json.py > server/src/search-unicode-tables.json
"""

import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def tables_module():
    spec = importlib.util.spec_from_file_location(
        "tables", os.path.join(HERE, "generate-search-unicode-tables.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main():
    tables = tables_module()
    classes, folds = tables.build_and_run()
    expected = 0x110000 - 0x800
    if len(classes) != expected:
        sys.exit(f"probed {len(classes)} scalars, expected {expected}")

    separators = sorted(s for s, k in classes.items() if k == tables.CLASS_SEPARATOR)
    ignored = sorted(s for s, k in classes.items() if k == tables.CLASS_IGNORED)
    spans = tables.contiguous(separators)

    header = {
        "note": "Generated by scripts/generate-search-unicode-tables-json.py from the same probe "
                "as Toj/Core/Search/SearchUnicodeTables.swift. Do not edit by hand.",
        "tokenize": tables.TOKENIZE,
        "counts": {
            "scalars": len(classes),
            "token": len(classes) - len(separators) - len(ignored),
            "separator": len(separators),
            "ignored": len(ignored),
            "separatorRanges": len(spans),
            "folds": len(folds),
        },
    }
    arrays = {
        "separatorRanges": [v for span in spans for v in span],
        "ignoredScalars": ignored,
        "foldPairs": [v for s, f in sorted(folds.items()) for v in (s, f)],
    }

    # Twelve numbers per line, as in the Swift file, so a regeneration diff points at the rows
    # that moved instead of one very long line.
    def rows(values):
        return ",\n".join(
            "    " + ",".join(str(v) for v in values[i : i + 12])
            for i in range(0, len(values), 12)
        )

    fields = [f"  {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}" for k, v in header.items()]
    fields += [f"  {json.dumps(k)}: [\n{rows(v)}\n  ]" for k, v in arrays.items()]
    print("{\n" + ",\n".join(fields) + "\n}")


if __name__ == "__main__":
    main()
